export const GOOD_CATEGORY = {
  APPLIANCES: "APPLIANCES",
  MUSIC: "MUSIC",
  BABY: "BABY",
  FURNITURE: "FURNITURE",
  STORAGE: "STORAGE",
  KITCHEN: "KITCHEN",
  COMPUTER: "COMPUTER",
  OTHER: "OTHER",
  TOOLS: "TOOLS",
} as const;

export type GoodCategory = typeof GOOD_CATEGORY[keyof typeof GOOD_CATEGORY];
